name: Bugzilla Test Suite

on:
  pull_request

jobs:
  test_sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install docker-compose
        run: sudo apt update && sudo apt install -y docker-compose
      - name: Build the Docker images
        run: docker compose -f docker-compose.test.yml build
      - name: Run sanity tests
        run: docker compose -f docker-compose.test.yml run --no-deps bugzilla6.test test_sanity t/*.t extensions/*/t/*.t

#  test_webservices:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Install docker-compose
#        run: sudo apt update && sudo apt install -y docker-compose
#      - name: Build the Docker images
#        run: docker compose -f docker-compose.test.yml build
#      - name: Run webservice tests
#        run: docker-compose -f docker-compose.test.yml run bugzilla6.test test_webservices

  test_bugzilla6_mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install docker-compose
        run: sudo apt update && sudo apt install -y docker-compose
      - name: Build the Docker images
        run: docker compose -f docker-compose.test.yml build
      - name: Run bmo specific tests
        run: docker-compose -f docker-compose.test.yml run -e CI=1 bugzilla6.test test_bmo -q -f t/bmo/*.t

  test_bugzilla6_pg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install docker-compose
        run: sudo apt update && sudo apt install -y docker-compose
      - name: Build the Docker images
        run: docker compose -f docker-compose.test-pg.yml build
      - name: Run bmo specific tests
        run: docker-compose -f docker-compose.test-pg.yml run -e CI=1 bugzilla6.test test_bmo -q -f t/bmo/*.t

